/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shareScreen_CODE */

#ifndef _Included_com_shareScreen_CODE
#define _Included_com_shareScreen_CODE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shareScreen_CODE
 * Method:    encode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shareScreen_CODE_encode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_shareScreen_CODE
 * Method:    decode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shareScreen_CODE_decode
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
